# Generated by Django 5.1.6 on 2025-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='vote',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
